### ISSUE TITLE
java.lang.NoClassDefFoundError: com/github/secretx33/sccfg/Config

### ISSUE THREAD

**Issue by Error404-RedRose** [SecretX33/sc-cfg#2]
I built your framework into a library .jar with all its dependencies satisfied but I'm getting this error
`java.lang.NoClassDefFoundError: com/github/secretx33/sccfg/Config`
the error is found at
`at me.nixeee.magictools.MagicTools.onEnable(MagicTools.java:19)`
but the enable looks like this
`PrivateVaultStorage storageconfig = Config.getConfig(PrivateVaultStorage.class);`
`Config.registerConfig(storageconfig);`

Any idea what is going on with this class not found error?

**Comment by Error404-RedRose** [comment]
when I get home I will go through the entire library and see if there are any missing class imports

**Comment by SecretX33** [comment]
You cannot register a config provided by the library as all configs instantiated by the library are already registered automatically, so this code would throw `ConfigOverrideException`.

As for building the library by hand, I would not advise that since you would have to provide all sc-cfg transitive dependencies by hand.
